:sectnums:
:nofooter:
:toc: left
:icons: font
:data-uri:
:source-highlighter: highlightjs
:stem: latexmath

= Company Manager

In this exercise you will create a Company-Manager. You can Send Products, Demote Employees, Promote Employees, View Organisations and Quit.

HINTS (READ)!!!

* Watch the video!
* You can use your own style for the output, behinde the scenes it should work as showed tho. 
* You do not need to list the Companies with 1, 2, ... you can get the input format for everything how you want
* THERE Are methoded twice implemented, they are overloaded with 1 parameter because the program needs alot of user inputs so some method were untestable. Thats why we created a a overloaded method with a already done user input. You can find the user input commented over the method!

[plantuml]
----
@startuml

hide empty methods

enum Position {
    Employee
    Manager
    VicePresident
    Owner
}

enum ProductType {
    None
    Banana
    Kiwi
    Chicken
}

class MyHashSet {
    -const int InitialBuckets
    -const int MaxDepth
    -List<T>[] _buckets
    -int _currentMaxDepth
    -int NoOfBuckets

    +MyHashSet(): this(InitialBuckets)
    -MyHashSet(int)
    +bool Add(T)
    +void Remove(T)
    +bool Contains(T)
    +List<T> GetValues()
    -void Grow()
    -GetBucketIndex(int)
    -List<T>[] CreateBuckets(int) {static}
}

class Company {
    +MyHashSet<Employee> Employees
    +MyHashSet<Product> Products
    +string Name
    +string[] s_options{static}
    +List<Company> s_companies{static}

    +Company(string)
    -void PrintProducts<T>(List<T>, string)
    -bool IsValidNumber<T>(int, List<T>)
    -void SelectProduct()
    -void SendProduct(Product)
    -void ViewOrganisation()
    -void SelectEmployee(bool)
    -void TransitEmployee(Employee, bool)
    -void PerfomOption(string)
    +Company SelectCompany(){static}
    +Company GetCompanyByName(string){static}
}

class Employee {
    +string Name [readonly]
    +Position Position {get; private set}

    +Employee(string,Position)
    +override string ToString()
    +void Demote()
    +void Promote()
}

class Products {
    +ProductType ProductType

    +Product(ProducType)
    +override string ToString()
}

class Initializer {
    +List<Company> InitializeCompanies(string){static}
}

Company "1" -- "n" Employee: employs
Company "1" -l- "n" Products: products
Products "1" -- "1" ProductType: productType
Employee "1" -r- "1" Position: position
Company "1" -r- "2" MyHashSet: myHashSet
@enduml
----
---
== `MyHashSet` class

* Here you'll just implement a generic HashSet.

== `Model` class

* Enum of ProductTypes, and enum of Position of an employee

== `Initializer` class

* Here are Companys initialized. Employees are randomly hired at companies, products are random initialized aswell. 

* Hints: Use the Random provider class

== `Employe` class

* In this class you can Demote an employee. If an employee with Position.Employee is demoted he will get fired! Owner can not be Promoted.
* Contains a ToString() method, printing the name and the position

== `Company` class

* Manages the employees and the products

* You are able to view the whole organisation. This will print all the employees and products with the .ToString() method to the console.

* You can select a product from the list. Only a valid number can be entered.

* You can send products to other companies

* You can select which company you want to manage.
